### PR TITLE
Replace phpDocumentator download url to use current stable version

### PR DESCRIPTION
**Pull request by koertho**
This PR replaces the phpDocumentator url in the docker image with the url of the current stable version of phpDocumentator from the offical repository.

### CODE REVIEW

**Comment by gpupo** [comment]
@koertho i have some the problems with that version. Until phpDocumentator release a more stable version, my build works

**Comment by koertho** [comment]
That's the current stable version (3.0.0) and it's significantly newer than the build you use in your docker file. But it's your repo, I can use my fork for now :)

**Comment by gpupo** [comment]
thanks @koertho . Merged

**Comment by gpupo** [comment]
at version 1.2 https://github.com/gpupo/actions-phpDocumentor/releases/tag/1.2

**Pull request merged**
